create sequence ci_sa_seq start with 1 increment by 50;
create table ci_acct (cre_dttm date, version bigint, acct_id varchar(12) not null, primary key (acct_id));
create table ci_ft (cur_amt numeric(38,2), freeze_dttm date, ft_id bigint generated by default as identity, sa_id bigint not null, version bigint, primary key (ft_id));
create table ci_sa (cre_dttm date, sa_id bigint not null, version bigint, acct_id varchar(12) not null, currency_cd varchar(255), sa_status varchar(255), primary key (sa_id));
alter table if exists ci_ft add constraint FKds6250qxjdi0k5halq8anfb2x foreign key (sa_id) references ci_sa;
alter table if exists ci_sa add constraint FK45yhavs63v1ji2v1j939e3y1i foreign key (acct_id) references ci_acct;

